print("Hello World")
print('University')
print("Hello"+" world")
print("I'm gk")
print('It is "very" good')
print("It is 'not good'")
print("you may good /// bad")
print("It's a good \"point\"")
print('It\'s a good \'point\'')
